apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-04-01T11:39:57Z","generation":1,"labels":{"app":"spring-music"},"name":"spring-music-deployment","namespace":"default","resourceVersion":"1558224","uid":"8ec73590-3c58-4edf-8039-4e699e779e71"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"spring-music-pod"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"spring-music-pod"}},"spec":{"containers":[{"command":["/bin/sh","-c","echo Loading Middleware \u0026\u0026 stress --cpu 2 --timeout 2s \u0026\u0026 java -jar spring-music.jar"],"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"dev"}],"image":"frenzy669/cpu_demo:latest","imagePullPolicy":"IfNotPresent","name":"spring-music","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-04-01T11:40:37Z","lastUpdateTime":"2025-04-01T11:40:37Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-04-01T11:39:57Z","lastUpdateTime":"2025-04-01T11:40:37Z","message":"ReplicaSet \"spring-music-deployment-556dcfd6bf\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-04-01T11:53:04Z"
  generation: 1
  labels:
    app: spring-music
  name: spring-music-deployment
  namespace: default
  resourceVersion: "1561919"
  uid: 5b325cd6-e73c-498d-b23c-919bb444bd7f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-music-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-music-pod
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo Loading Middleware && stress --cpu 2 --timeout 2s && java -jar spring-music.jar
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        image: frenzy669/cpu_demo:latest
        imagePullPolicy: IfNotPresent
        name: spring-music
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-01T12:00:15Z"
    lastUpdateTime: "2025-04-01T12:00:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-01T11:53:04Z"
    lastUpdateTime: "2025-04-01T12:00:15Z"
    message: ReplicaSet "spring-music-deployment-556dcfd6bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
