apiVersion: v1
kind: Namespace
metadata:
  name: grus
  labels:
    name: checkpoint-operator
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    openshift.io/node-selector: ""
    openshift.io/description: "Namespace for Checkpoint Operator"
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: checkpoint-operator-scc
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostDirVolumePlugin: true
allowHostPID: true
allowHostIPC: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:checkpoint-operator:default
