apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-apiserver-checkpoints
  labels:
    {{- include "grus.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes/checkpoint
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-apiserver-checkpoints
  labels:
    {{- include "grus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-apiserver-checkpoints
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-apiserver
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-apiserver