apiVersion: v1
kind: Service
metadata:
  name: {{ include "grus.fullname" . }}
  labels:
    {{- include "grus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: api
      protocol: TCP
      name: api
    - port: 80
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "grus.selectorLabels" . | nindent 4 }}
